default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: env UV_CACHE_DIR=/tmp/uv-cache uv run -q ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff-format
        entry: env UV_CACHE_DIR=/tmp/uv-cache uv run -q ruff format
        language: system
        types: [python]

      - id: ty
        name: ty
        entry: env UV_CACHE_DIR=/tmp/uv-cache uv run -q ty check --ignore invalid-argument-type --ignore possibly-missing-attribute --ignore no-matching-overload --ignore invalid-return-type --ignore invalid-method-override --ignore invalid-assignment pulp_lparray
        language: system
        pass_filenames: false

      - id: ty-examples
        name: ty-examples
        entry: env UV_CACHE_DIR=/tmp/uv-cache uv run -q ty check --ignore invalid-argument-type --ignore invalid-method-override --ignore invalid-assignment examples
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: env UV_CACHE_DIR=/tmp/uv-cache uv run -q pytest
        language: system
        pass_filenames: false
